version: "3.1"

services:
  # More info at https://github.com/wodby/php
  # We don't want their drupal-php image as that ships with a Drush inside.
  php:
    image: wodby/php:${PHP_TAG-7.4-dev}
    container_name: ${PROJECT_NAME-ac}_php
    environment:
      PHP_SENDMAIL_PATH: /dev/null
      COLUMNS: ${COLUMNS-80} # Set 80 columns for docker exec -it.
      ## Read instructions at https://wodby.com/docs/stacks/drupal/local/#debugging-cli-requests
      PHP_XDEBUG:
      PHP_XDEBUG_MODE:
      PHP_IDE_CONFIG:
      PHP_XDEBUG_START_WITH_REQUEST:
      PHP_XDEBUG_REMOTE_HOST:
    volumes:
      - ./:/var/www/html:${VOLUME_FLAGS-cached}
